/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EspelhosLedRouteImport } from './routes/espelhos-led'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as PortasDeVidroIndexRouteImport } from './routes/portas-de-vidro.index'
import { Route as EspelhosIndexRouteImport } from './routes/espelhos.index'
import { Route as BoxIncolorIndexRouteImport } from './routes/box-incolor.index'
import { Route as BoxFumeIndexRouteImport } from './routes/box-fume.index'
import { Route as BoxDeBanheiroIndexRouteImport } from './routes/box-de-banheiro.index'
import { Route as ServicosBairroRouteImport } from './routes/servicos.$bairro'
import { Route as ProjetosResidencialRouteImport } from './routes/projetos.residencial'
import { Route as ProjetosGuardaCorpoRouteImport } from './routes/projetos.guarda-corpo'
import { Route as ProjetosFechamentoSacadaRouteImport } from './routes/projetos.fechamento-sacada'
import { Route as ProjetosEscritoriosRouteImport } from './routes/projetos.escritorios'
import { Route as ProjetosComercialRouteImport } from './routes/projetos.comercial'
import { Route as ProjetosCoberturasRouteImport } from './routes/projetos.coberturas'
import { Route as ProjetosModeloRouteImport } from './routes/projetos.$modelo'
import { Route as PortasDeVidroVisionRouteImport } from './routes/portas-de-vidro.vision'
import { Route as PortasDeVidroVersatikRouteImport } from './routes/portas-de-vidro.versatik'
import { Route as PortasDeVidroNobreRouteImport } from './routes/portas-de-vidro.nobre'
import { Route as PortasDeVidroFlexRouteImport } from './routes/portas-de-vidro.flex'
import { Route as PortasDeVidroCorrerRouteImport } from './routes/portas-de-vidro.correr'
import { Route as PortasDeVidroCertaRouteImport } from './routes/portas-de-vidro.certa'
import { Route as PortasDeVidroAbrirRouteImport } from './routes/portas-de-vidro.abrir'
import { Route as PortasDeVidroModeloRouteImport } from './routes/portas-de-vidro.$modelo'
import { Route as EspelhosPainelRouteImport } from './routes/espelhos.painel'
import { Route as EspelhosOrganicoRouteImport } from './routes/espelhos.organico'
import { Route as EspelhosLapidadoRouteImport } from './routes/espelhos.lapidado'
import { Route as EspelhosBisoteRouteImport } from './routes/espelhos.bisote'
import { Route as EspelhosBanheiroRouteImport } from './routes/espelhos.banheiro'
import { Route as EspelhosModeloRouteImport } from './routes/espelhos.$modelo'
import { Route as BoxDeBanheiroTransferRouteImport } from './routes/box-de-banheiro.transfer'
import { Route as BoxDeBanheiroTradicionalRouteImport } from './routes/box-de-banheiro.tradicional'
import { Route as BoxDeBanheiroSecureBoxRouteImport } from './routes/box-de-banheiro.secure-box'
import { Route as BoxDeBanheiroPisoTetoRouteImport } from './routes/box-de-banheiro.piso-teto'
import { Route as BoxDeBanheiroNobreRouteImport } from './routes/box-de-banheiro.nobre'
import { Route as BoxDeBanheiroFlexRouteImport } from './routes/box-de-banheiro.flex'
import { Route as BoxDeBanheiroEleganceRouteImport } from './routes/box-de-banheiro.elegance'
import { Route as BoxDeBanheiroModeloRouteImport } from './routes/box-de-banheiro.$modelo'
import { Route as BlogSecureBoxPeliculaProtecaoRouteImport } from './routes/blog_.secure-box-pelicula-protecao'
import { Route as BlogManutencaoBoxBanheiroRouteImport } from './routes/blog_.manutencao-box-banheiro'
import { Route as BlogFastVidroHistoriaRouteImport } from './routes/blog_.fast-vidro-historia'
import { Route as BlogEspelhosLedSobMedidaRouteImport } from './routes/blog_.espelhos-led-sob-medida'
import { Route as BlogCorBoxIncolorFumeVerdeBronzeRouteImport } from './routes/blog_.cor-box-incolor-fume-verde-bronze'
import { Route as BlogBoxTradicionalVsFlexRouteImport } from './routes/blog_.box-tradicional-vs-flex'
import { Route as BlogBoxConvencionalVsAteOTetoRouteImport } from './routes/blog_.box-convencional-vs-ate-o-teto'
import { Route as BlogBoxBanheiroZonaNorteRouteImport } from './routes/blog_.box-banheiro-zona-norte'
import { Route as BlogBoxBanheiroVilaGuilhermeRouteImport } from './routes/blog_.box-banheiro-vila-guilherme'
import { Route as BlogBoxBanheiroVidroSantanaRouteImport } from './routes/blog_.box-banheiro-vidro-santana'
import { Route as BlogBoxBanheiroTucuruviRouteImport } from './routes/blog_.box-banheiro-tucuruvi'
import { Route as BlogBoxBanheiroMandaquiRouteImport } from './routes/blog_.box-banheiro-mandaqui'
import { Route as BlogBoxBanheiroJardimSaoPauloRouteImport } from './routes/blog_.box-banheiro-jardim-sao-paulo'
import { Route as BlogBoxBanheiroCasaVerdeImirimRouteImport } from './routes/blog_.box-banheiro-casa-verde-imirim'
import { Route as BlogBox3FolhasSistemaVersatikRouteImport } from './routes/blog_.box-3-folhas-sistema-versatik'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosLedRoute = EspelhosLedRouteImport.update({
  id: '/espelhos-led',
  path: '/espelhos-led',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroIndexRoute = PortasDeVidroIndexRouteImport.update({
  id: '/portas-de-vidro/',
  path: '/portas-de-vidro/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosIndexRoute = EspelhosIndexRouteImport.update({
  id: '/espelhos/',
  path: '/espelhos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxIncolorIndexRoute = BoxIncolorIndexRouteImport.update({
  id: '/box-incolor/',
  path: '/box-incolor/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxFumeIndexRoute = BoxFumeIndexRouteImport.update({
  id: '/box-fume/',
  path: '/box-fume/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroIndexRoute = BoxDeBanheiroIndexRouteImport.update({
  id: '/box-de-banheiro/',
  path: '/box-de-banheiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosBairroRoute = ServicosBairroRouteImport.update({
  id: '/servicos/$bairro',
  path: '/servicos/$bairro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosResidencialRoute = ProjetosResidencialRouteImport.update({
  id: '/projetos/residencial',
  path: '/projetos/residencial',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosGuardaCorpoRoute = ProjetosGuardaCorpoRouteImport.update({
  id: '/projetos/guarda-corpo',
  path: '/projetos/guarda-corpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosFechamentoSacadaRoute =
  ProjetosFechamentoSacadaRouteImport.update({
    id: '/projetos/fechamento-sacada',
    path: '/projetos/fechamento-sacada',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjetosEscritoriosRoute = ProjetosEscritoriosRouteImport.update({
  id: '/projetos/escritorios',
  path: '/projetos/escritorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosComercialRoute = ProjetosComercialRouteImport.update({
  id: '/projetos/comercial',
  path: '/projetos/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosCoberturasRoute = ProjetosCoberturasRouteImport.update({
  id: '/projetos/coberturas',
  path: '/projetos/coberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosModeloRoute = ProjetosModeloRouteImport.update({
  id: '/projetos/$modelo',
  path: '/projetos/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroVisionRoute = PortasDeVidroVisionRouteImport.update({
  id: '/portas-de-vidro/vision',
  path: '/portas-de-vidro/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroVersatikRoute = PortasDeVidroVersatikRouteImport.update({
  id: '/portas-de-vidro/versatik',
  path: '/portas-de-vidro/versatik',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroNobreRoute = PortasDeVidroNobreRouteImport.update({
  id: '/portas-de-vidro/nobre',
  path: '/portas-de-vidro/nobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroFlexRoute = PortasDeVidroFlexRouteImport.update({
  id: '/portas-de-vidro/flex',
  path: '/portas-de-vidro/flex',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroCorrerRoute = PortasDeVidroCorrerRouteImport.update({
  id: '/portas-de-vidro/correr',
  path: '/portas-de-vidro/correr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroCertaRoute = PortasDeVidroCertaRouteImport.update({
  id: '/portas-de-vidro/certa',
  path: '/portas-de-vidro/certa',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroAbrirRoute = PortasDeVidroAbrirRouteImport.update({
  id: '/portas-de-vidro/abrir',
  path: '/portas-de-vidro/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroModeloRoute = PortasDeVidroModeloRouteImport.update({
  id: '/portas-de-vidro/$modelo',
  path: '/portas-de-vidro/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosPainelRoute = EspelhosPainelRouteImport.update({
  id: '/espelhos/painel',
  path: '/espelhos/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosOrganicoRoute = EspelhosOrganicoRouteImport.update({
  id: '/espelhos/organico',
  path: '/espelhos/organico',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosLapidadoRoute = EspelhosLapidadoRouteImport.update({
  id: '/espelhos/lapidado',
  path: '/espelhos/lapidado',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosBisoteRoute = EspelhosBisoteRouteImport.update({
  id: '/espelhos/bisote',
  path: '/espelhos/bisote',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosBanheiroRoute = EspelhosBanheiroRouteImport.update({
  id: '/espelhos/banheiro',
  path: '/espelhos/banheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosModeloRoute = EspelhosModeloRouteImport.update({
  id: '/espelhos/$modelo',
  path: '/espelhos/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroTransferRoute = BoxDeBanheiroTransferRouteImport.update({
  id: '/box-de-banheiro/transfer',
  path: '/box-de-banheiro/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroTradicionalRoute =
  BoxDeBanheiroTradicionalRouteImport.update({
    id: '/box-de-banheiro/tradicional',
    path: '/box-de-banheiro/tradicional',
    getParentRoute: () => rootRouteImport,
  } as any)
const BoxDeBanheiroSecureBoxRoute = BoxDeBanheiroSecureBoxRouteImport.update({
  id: '/box-de-banheiro/secure-box',
  path: '/box-de-banheiro/secure-box',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroPisoTetoRoute = BoxDeBanheiroPisoTetoRouteImport.update({
  id: '/box-de-banheiro/piso-teto',
  path: '/box-de-banheiro/piso-teto',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroNobreRoute = BoxDeBanheiroNobreRouteImport.update({
  id: '/box-de-banheiro/nobre',
  path: '/box-de-banheiro/nobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroFlexRoute = BoxDeBanheiroFlexRouteImport.update({
  id: '/box-de-banheiro/flex',
  path: '/box-de-banheiro/flex',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroEleganceRoute = BoxDeBanheiroEleganceRouteImport.update({
  id: '/box-de-banheiro/elegance',
  path: '/box-de-banheiro/elegance',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroModeloRoute = BoxDeBanheiroModeloRouteImport.update({
  id: '/box-de-banheiro/$modelo',
  path: '/box-de-banheiro/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSecureBoxPeliculaProtecaoRoute =
  BlogSecureBoxPeliculaProtecaoRouteImport.update({
    id: '/blog_/secure-box-pelicula-protecao',
    path: '/blog/secure-box-pelicula-protecao',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogManutencaoBoxBanheiroRoute =
  BlogManutencaoBoxBanheiroRouteImport.update({
    id: '/blog_/manutencao-box-banheiro',
    path: '/blog/manutencao-box-banheiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFastVidroHistoriaRoute = BlogFastVidroHistoriaRouteImport.update({
  id: '/blog_/fast-vidro-historia',
  path: '/blog/fast-vidro-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEspelhosLedSobMedidaRoute =
  BlogEspelhosLedSobMedidaRouteImport.update({
    id: '/blog_/espelhos-led-sob-medida',
    path: '/blog/espelhos-led-sob-medida',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCorBoxIncolorFumeVerdeBronzeRoute =
  BlogCorBoxIncolorFumeVerdeBronzeRouteImport.update({
    id: '/blog_/cor-box-incolor-fume-verde-bronze',
    path: '/blog/cor-box-incolor-fume-verde-bronze',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxTradicionalVsFlexRoute =
  BlogBoxTradicionalVsFlexRouteImport.update({
    id: '/blog_/box-tradicional-vs-flex',
    path: '/blog/box-tradicional-vs-flex',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxConvencionalVsAteOTetoRoute =
  BlogBoxConvencionalVsAteOTetoRouteImport.update({
    id: '/blog_/box-convencional-vs-ate-o-teto',
    path: '/blog/box-convencional-vs-ate-o-teto',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxBanheiroZonaNorteRoute =
  BlogBoxBanheiroZonaNorteRouteImport.update({
    id: '/blog_/box-banheiro-zona-norte',
    path: '/blog/box-banheiro-zona-norte',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxBanheiroVilaGuilhermeRoute =
  BlogBoxBanheiroVilaGuilhermeRouteImport.update({
    id: '/blog_/box-banheiro-vila-guilherme',
    path: '/blog/box-banheiro-vila-guilherme',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxBanheiroVidroSantanaRoute =
  BlogBoxBanheiroVidroSantanaRouteImport.update({
    id: '/blog_/box-banheiro-vidro-santana',
    path: '/blog/box-banheiro-vidro-santana',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxBanheiroTucuruviRoute = BlogBoxBanheiroTucuruviRouteImport.update({
  id: '/blog_/box-banheiro-tucuruvi',
  path: '/blog/box-banheiro-tucuruvi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBoxBanheiroMandaquiRoute = BlogBoxBanheiroMandaquiRouteImport.update({
  id: '/blog_/box-banheiro-mandaqui',
  path: '/blog/box-banheiro-mandaqui',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBoxBanheiroJardimSaoPauloRoute =
  BlogBoxBanheiroJardimSaoPauloRouteImport.update({
    id: '/blog_/box-banheiro-jardim-sao-paulo',
    path: '/blog/box-banheiro-jardim-sao-paulo',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBoxBanheiroCasaVerdeImirimRoute =
  BlogBoxBanheiroCasaVerdeImirimRouteImport.update({
    id: '/blog_/box-banheiro-casa-verde-imirim',
    path: '/blog/box-banheiro-casa-verde-imirim',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBox3FolhasSistemaVersatikRoute =
  BlogBox3FolhasSistemaVersatikRouteImport.update({
    id: '/blog_/box-3-folhas-sistema-versatik',
    path: '/blog/box-3-folhas-sistema-versatik',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/espelhos-led': typeof EspelhosLedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/box-3-folhas-sistema-versatik': typeof BlogBox3FolhasSistemaVersatikRoute
  '/blog/box-banheiro-casa-verde-imirim': typeof BlogBoxBanheiroCasaVerdeImirimRoute
  '/blog/box-banheiro-jardim-sao-paulo': typeof BlogBoxBanheiroJardimSaoPauloRoute
  '/blog/box-banheiro-mandaqui': typeof BlogBoxBanheiroMandaquiRoute
  '/blog/box-banheiro-tucuruvi': typeof BlogBoxBanheiroTucuruviRoute
  '/blog/box-banheiro-vidro-santana': typeof BlogBoxBanheiroVidroSantanaRoute
  '/blog/box-banheiro-vila-guilherme': typeof BlogBoxBanheiroVilaGuilhermeRoute
  '/blog/box-banheiro-zona-norte': typeof BlogBoxBanheiroZonaNorteRoute
  '/blog/box-convencional-vs-ate-o-teto': typeof BlogBoxConvencionalVsAteOTetoRoute
  '/blog/box-tradicional-vs-flex': typeof BlogBoxTradicionalVsFlexRoute
  '/blog/cor-box-incolor-fume-verde-bronze': typeof BlogCorBoxIncolorFumeVerdeBronzeRoute
  '/blog/espelhos-led-sob-medida': typeof BlogEspelhosLedSobMedidaRoute
  '/blog/fast-vidro-historia': typeof BlogFastVidroHistoriaRoute
  '/blog/manutencao-box-banheiro': typeof BlogManutencaoBoxBanheiroRoute
  '/blog/secure-box-pelicula-protecao': typeof BlogSecureBoxPeliculaProtecaoRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/box-de-banheiro/elegance': typeof BoxDeBanheiroEleganceRoute
  '/box-de-banheiro/flex': typeof BoxDeBanheiroFlexRoute
  '/box-de-banheiro/nobre': typeof BoxDeBanheiroNobreRoute
  '/box-de-banheiro/piso-teto': typeof BoxDeBanheiroPisoTetoRoute
  '/box-de-banheiro/secure-box': typeof BoxDeBanheiroSecureBoxRoute
  '/box-de-banheiro/tradicional': typeof BoxDeBanheiroTradicionalRoute
  '/box-de-banheiro/transfer': typeof BoxDeBanheiroTransferRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/espelhos/banheiro': typeof EspelhosBanheiroRoute
  '/espelhos/bisote': typeof EspelhosBisoteRoute
  '/espelhos/lapidado': typeof EspelhosLapidadoRoute
  '/espelhos/organico': typeof EspelhosOrganicoRoute
  '/espelhos/painel': typeof EspelhosPainelRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/portas-de-vidro/abrir': typeof PortasDeVidroAbrirRoute
  '/portas-de-vidro/certa': typeof PortasDeVidroCertaRoute
  '/portas-de-vidro/correr': typeof PortasDeVidroCorrerRoute
  '/portas-de-vidro/flex': typeof PortasDeVidroFlexRoute
  '/portas-de-vidro/nobre': typeof PortasDeVidroNobreRoute
  '/portas-de-vidro/versatik': typeof PortasDeVidroVersatikRoute
  '/portas-de-vidro/vision': typeof PortasDeVidroVisionRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
  '/projetos/coberturas': typeof ProjetosCoberturasRoute
  '/projetos/comercial': typeof ProjetosComercialRoute
  '/projetos/escritorios': typeof ProjetosEscritoriosRoute
  '/projetos/fechamento-sacada': typeof ProjetosFechamentoSacadaRoute
  '/projetos/guarda-corpo': typeof ProjetosGuardaCorpoRoute
  '/projetos/residencial': typeof ProjetosResidencialRoute
  '/servicos/$bairro': typeof ServicosBairroRoute
  '/box-de-banheiro/': typeof BoxDeBanheiroIndexRoute
  '/box-fume/': typeof BoxFumeIndexRoute
  '/box-incolor/': typeof BoxIncolorIndexRoute
  '/espelhos/': typeof EspelhosIndexRoute
  '/portas-de-vidro/': typeof PortasDeVidroIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/espelhos-led': typeof EspelhosLedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/box-3-folhas-sistema-versatik': typeof BlogBox3FolhasSistemaVersatikRoute
  '/blog/box-banheiro-casa-verde-imirim': typeof BlogBoxBanheiroCasaVerdeImirimRoute
  '/blog/box-banheiro-jardim-sao-paulo': typeof BlogBoxBanheiroJardimSaoPauloRoute
  '/blog/box-banheiro-mandaqui': typeof BlogBoxBanheiroMandaquiRoute
  '/blog/box-banheiro-tucuruvi': typeof BlogBoxBanheiroTucuruviRoute
  '/blog/box-banheiro-vidro-santana': typeof BlogBoxBanheiroVidroSantanaRoute
  '/blog/box-banheiro-vila-guilherme': typeof BlogBoxBanheiroVilaGuilhermeRoute
  '/blog/box-banheiro-zona-norte': typeof BlogBoxBanheiroZonaNorteRoute
  '/blog/box-convencional-vs-ate-o-teto': typeof BlogBoxConvencionalVsAteOTetoRoute
  '/blog/box-tradicional-vs-flex': typeof BlogBoxTradicionalVsFlexRoute
  '/blog/cor-box-incolor-fume-verde-bronze': typeof BlogCorBoxIncolorFumeVerdeBronzeRoute
  '/blog/espelhos-led-sob-medida': typeof BlogEspelhosLedSobMedidaRoute
  '/blog/fast-vidro-historia': typeof BlogFastVidroHistoriaRoute
  '/blog/manutencao-box-banheiro': typeof BlogManutencaoBoxBanheiroRoute
  '/blog/secure-box-pelicula-protecao': typeof BlogSecureBoxPeliculaProtecaoRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/box-de-banheiro/elegance': typeof BoxDeBanheiroEleganceRoute
  '/box-de-banheiro/flex': typeof BoxDeBanheiroFlexRoute
  '/box-de-banheiro/nobre': typeof BoxDeBanheiroNobreRoute
  '/box-de-banheiro/piso-teto': typeof BoxDeBanheiroPisoTetoRoute
  '/box-de-banheiro/secure-box': typeof BoxDeBanheiroSecureBoxRoute
  '/box-de-banheiro/tradicional': typeof BoxDeBanheiroTradicionalRoute
  '/box-de-banheiro/transfer': typeof BoxDeBanheiroTransferRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/espelhos/banheiro': typeof EspelhosBanheiroRoute
  '/espelhos/bisote': typeof EspelhosBisoteRoute
  '/espelhos/lapidado': typeof EspelhosLapidadoRoute
  '/espelhos/organico': typeof EspelhosOrganicoRoute
  '/espelhos/painel': typeof EspelhosPainelRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/portas-de-vidro/abrir': typeof PortasDeVidroAbrirRoute
  '/portas-de-vidro/certa': typeof PortasDeVidroCertaRoute
  '/portas-de-vidro/correr': typeof PortasDeVidroCorrerRoute
  '/portas-de-vidro/flex': typeof PortasDeVidroFlexRoute
  '/portas-de-vidro/nobre': typeof PortasDeVidroNobreRoute
  '/portas-de-vidro/versatik': typeof PortasDeVidroVersatikRoute
  '/portas-de-vidro/vision': typeof PortasDeVidroVisionRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
  '/projetos/coberturas': typeof ProjetosCoberturasRoute
  '/projetos/comercial': typeof ProjetosComercialRoute
  '/projetos/escritorios': typeof ProjetosEscritoriosRoute
  '/projetos/fechamento-sacada': typeof ProjetosFechamentoSacadaRoute
  '/projetos/guarda-corpo': typeof ProjetosGuardaCorpoRoute
  '/projetos/residencial': typeof ProjetosResidencialRoute
  '/servicos/$bairro': typeof ServicosBairroRoute
  '/box-de-banheiro': typeof BoxDeBanheiroIndexRoute
  '/box-fume': typeof BoxFumeIndexRoute
  '/box-incolor': typeof BoxIncolorIndexRoute
  '/espelhos': typeof EspelhosIndexRoute
  '/portas-de-vidro': typeof PortasDeVidroIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/espelhos-led': typeof EspelhosLedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog_/box-3-folhas-sistema-versatik': typeof BlogBox3FolhasSistemaVersatikRoute
  '/blog_/box-banheiro-casa-verde-imirim': typeof BlogBoxBanheiroCasaVerdeImirimRoute
  '/blog_/box-banheiro-jardim-sao-paulo': typeof BlogBoxBanheiroJardimSaoPauloRoute
  '/blog_/box-banheiro-mandaqui': typeof BlogBoxBanheiroMandaquiRoute
  '/blog_/box-banheiro-tucuruvi': typeof BlogBoxBanheiroTucuruviRoute
  '/blog_/box-banheiro-vidro-santana': typeof BlogBoxBanheiroVidroSantanaRoute
  '/blog_/box-banheiro-vila-guilherme': typeof BlogBoxBanheiroVilaGuilhermeRoute
  '/blog_/box-banheiro-zona-norte': typeof BlogBoxBanheiroZonaNorteRoute
  '/blog_/box-convencional-vs-ate-o-teto': typeof BlogBoxConvencionalVsAteOTetoRoute
  '/blog_/box-tradicional-vs-flex': typeof BlogBoxTradicionalVsFlexRoute
  '/blog_/cor-box-incolor-fume-verde-bronze': typeof BlogCorBoxIncolorFumeVerdeBronzeRoute
  '/blog_/espelhos-led-sob-medida': typeof BlogEspelhosLedSobMedidaRoute
  '/blog_/fast-vidro-historia': typeof BlogFastVidroHistoriaRoute
  '/blog_/manutencao-box-banheiro': typeof BlogManutencaoBoxBanheiroRoute
  '/blog_/secure-box-pelicula-protecao': typeof BlogSecureBoxPeliculaProtecaoRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/box-de-banheiro/elegance': typeof BoxDeBanheiroEleganceRoute
  '/box-de-banheiro/flex': typeof BoxDeBanheiroFlexRoute
  '/box-de-banheiro/nobre': typeof BoxDeBanheiroNobreRoute
  '/box-de-banheiro/piso-teto': typeof BoxDeBanheiroPisoTetoRoute
  '/box-de-banheiro/secure-box': typeof BoxDeBanheiroSecureBoxRoute
  '/box-de-banheiro/tradicional': typeof BoxDeBanheiroTradicionalRoute
  '/box-de-banheiro/transfer': typeof BoxDeBanheiroTransferRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/espelhos/banheiro': typeof EspelhosBanheiroRoute
  '/espelhos/bisote': typeof EspelhosBisoteRoute
  '/espelhos/lapidado': typeof EspelhosLapidadoRoute
  '/espelhos/organico': typeof EspelhosOrganicoRoute
  '/espelhos/painel': typeof EspelhosPainelRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/portas-de-vidro/abrir': typeof PortasDeVidroAbrirRoute
  '/portas-de-vidro/certa': typeof PortasDeVidroCertaRoute
  '/portas-de-vidro/correr': typeof PortasDeVidroCorrerRoute
  '/portas-de-vidro/flex': typeof PortasDeVidroFlexRoute
  '/portas-de-vidro/nobre': typeof PortasDeVidroNobreRoute
  '/portas-de-vidro/versatik': typeof PortasDeVidroVersatikRoute
  '/portas-de-vidro/vision': typeof PortasDeVidroVisionRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
  '/projetos/coberturas': typeof ProjetosCoberturasRoute
  '/projetos/comercial': typeof ProjetosComercialRoute
  '/projetos/escritorios': typeof ProjetosEscritoriosRoute
  '/projetos/fechamento-sacada': typeof ProjetosFechamentoSacadaRoute
  '/projetos/guarda-corpo': typeof ProjetosGuardaCorpoRoute
  '/projetos/residencial': typeof ProjetosResidencialRoute
  '/servicos/$bairro': typeof ServicosBairroRoute
  '/box-de-banheiro/': typeof BoxDeBanheiroIndexRoute
  '/box-fume/': typeof BoxFumeIndexRoute
  '/box-incolor/': typeof BoxIncolorIndexRoute
  '/espelhos/': typeof EspelhosIndexRoute
  '/portas-de-vidro/': typeof PortasDeVidroIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/espelhos-led'
    | '/sitemap.xml'
    | '/blog/box-3-folhas-sistema-versatik'
    | '/blog/box-banheiro-casa-verde-imirim'
    | '/blog/box-banheiro-jardim-sao-paulo'
    | '/blog/box-banheiro-mandaqui'
    | '/blog/box-banheiro-tucuruvi'
    | '/blog/box-banheiro-vidro-santana'
    | '/blog/box-banheiro-vila-guilherme'
    | '/blog/box-banheiro-zona-norte'
    | '/blog/box-convencional-vs-ate-o-teto'
    | '/blog/box-tradicional-vs-flex'
    | '/blog/cor-box-incolor-fume-verde-bronze'
    | '/blog/espelhos-led-sob-medida'
    | '/blog/fast-vidro-historia'
    | '/blog/manutencao-box-banheiro'
    | '/blog/secure-box-pelicula-protecao'
    | '/box-de-banheiro/$modelo'
    | '/box-de-banheiro/elegance'
    | '/box-de-banheiro/flex'
    | '/box-de-banheiro/nobre'
    | '/box-de-banheiro/piso-teto'
    | '/box-de-banheiro/secure-box'
    | '/box-de-banheiro/tradicional'
    | '/box-de-banheiro/transfer'
    | '/espelhos/$modelo'
    | '/espelhos/banheiro'
    | '/espelhos/bisote'
    | '/espelhos/lapidado'
    | '/espelhos/organico'
    | '/espelhos/painel'
    | '/portas-de-vidro/$modelo'
    | '/portas-de-vidro/abrir'
    | '/portas-de-vidro/certa'
    | '/portas-de-vidro/correr'
    | '/portas-de-vidro/flex'
    | '/portas-de-vidro/nobre'
    | '/portas-de-vidro/versatik'
    | '/portas-de-vidro/vision'
    | '/projetos/$modelo'
    | '/projetos/coberturas'
    | '/projetos/comercial'
    | '/projetos/escritorios'
    | '/projetos/fechamento-sacada'
    | '/projetos/guarda-corpo'
    | '/projetos/residencial'
    | '/servicos/$bairro'
    | '/box-de-banheiro/'
    | '/box-fume/'
    | '/box-incolor/'
    | '/espelhos/'
    | '/portas-de-vidro/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/espelhos-led'
    | '/sitemap.xml'
    | '/blog/box-3-folhas-sistema-versatik'
    | '/blog/box-banheiro-casa-verde-imirim'
    | '/blog/box-banheiro-jardim-sao-paulo'
    | '/blog/box-banheiro-mandaqui'
    | '/blog/box-banheiro-tucuruvi'
    | '/blog/box-banheiro-vidro-santana'
    | '/blog/box-banheiro-vila-guilherme'
    | '/blog/box-banheiro-zona-norte'
    | '/blog/box-convencional-vs-ate-o-teto'
    | '/blog/box-tradicional-vs-flex'
    | '/blog/cor-box-incolor-fume-verde-bronze'
    | '/blog/espelhos-led-sob-medida'
    | '/blog/fast-vidro-historia'
    | '/blog/manutencao-box-banheiro'
    | '/blog/secure-box-pelicula-protecao'
    | '/box-de-banheiro/$modelo'
    | '/box-de-banheiro/elegance'
    | '/box-de-banheiro/flex'
    | '/box-de-banheiro/nobre'
    | '/box-de-banheiro/piso-teto'
    | '/box-de-banheiro/secure-box'
    | '/box-de-banheiro/tradicional'
    | '/box-de-banheiro/transfer'
    | '/espelhos/$modelo'
    | '/espelhos/banheiro'
    | '/espelhos/bisote'
    | '/espelhos/lapidado'
    | '/espelhos/organico'
    | '/espelhos/painel'
    | '/portas-de-vidro/$modelo'
    | '/portas-de-vidro/abrir'
    | '/portas-de-vidro/certa'
    | '/portas-de-vidro/correr'
    | '/portas-de-vidro/flex'
    | '/portas-de-vidro/nobre'
    | '/portas-de-vidro/versatik'
    | '/portas-de-vidro/vision'
    | '/projetos/$modelo'
    | '/projetos/coberturas'
    | '/projetos/comercial'
    | '/projetos/escritorios'
    | '/projetos/fechamento-sacada'
    | '/projetos/guarda-corpo'
    | '/projetos/residencial'
    | '/servicos/$bairro'
    | '/box-de-banheiro'
    | '/box-fume'
    | '/box-incolor'
    | '/espelhos'
    | '/portas-de-vidro'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/espelhos-led'
    | '/sitemap.xml'
    | '/blog_/box-3-folhas-sistema-versatik'
    | '/blog_/box-banheiro-casa-verde-imirim'
    | '/blog_/box-banheiro-jardim-sao-paulo'
    | '/blog_/box-banheiro-mandaqui'
    | '/blog_/box-banheiro-tucuruvi'
    | '/blog_/box-banheiro-vidro-santana'
    | '/blog_/box-banheiro-vila-guilherme'
    | '/blog_/box-banheiro-zona-norte'
    | '/blog_/box-convencional-vs-ate-o-teto'
    | '/blog_/box-tradicional-vs-flex'
    | '/blog_/cor-box-incolor-fume-verde-bronze'
    | '/blog_/espelhos-led-sob-medida'
    | '/blog_/fast-vidro-historia'
    | '/blog_/manutencao-box-banheiro'
    | '/blog_/secure-box-pelicula-protecao'
    | '/box-de-banheiro/$modelo'
    | '/box-de-banheiro/elegance'
    | '/box-de-banheiro/flex'
    | '/box-de-banheiro/nobre'
    | '/box-de-banheiro/piso-teto'
    | '/box-de-banheiro/secure-box'
    | '/box-de-banheiro/tradicional'
    | '/box-de-banheiro/transfer'
    | '/espelhos/$modelo'
    | '/espelhos/banheiro'
    | '/espelhos/bisote'
    | '/espelhos/lapidado'
    | '/espelhos/organico'
    | '/espelhos/painel'
    | '/portas-de-vidro/$modelo'
    | '/portas-de-vidro/abrir'
    | '/portas-de-vidro/certa'
    | '/portas-de-vidro/correr'
    | '/portas-de-vidro/flex'
    | '/portas-de-vidro/nobre'
    | '/portas-de-vidro/versatik'
    | '/portas-de-vidro/vision'
    | '/projetos/$modelo'
    | '/projetos/coberturas'
    | '/projetos/comercial'
    | '/projetos/escritorios'
    | '/projetos/fechamento-sacada'
    | '/projetos/guarda-corpo'
    | '/projetos/residencial'
    | '/servicos/$bairro'
    | '/box-de-banheiro/'
    | '/box-fume/'
    | '/box-incolor/'
    | '/espelhos/'
    | '/portas-de-vidro/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  EspelhosLedRoute: typeof EspelhosLedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogBox3FolhasSistemaVersatikRoute: typeof BlogBox3FolhasSistemaVersatikRoute
  BlogBoxBanheiroCasaVerdeImirimRoute: typeof BlogBoxBanheiroCasaVerdeImirimRoute
  BlogBoxBanheiroJardimSaoPauloRoute: typeof BlogBoxBanheiroJardimSaoPauloRoute
  BlogBoxBanheiroMandaquiRoute: typeof BlogBoxBanheiroMandaquiRoute
  BlogBoxBanheiroTucuruviRoute: typeof BlogBoxBanheiroTucuruviRoute
  BlogBoxBanheiroVidroSantanaRoute: typeof BlogBoxBanheiroVidroSantanaRoute
  BlogBoxBanheiroVilaGuilhermeRoute: typeof BlogBoxBanheiroVilaGuilhermeRoute
  BlogBoxBanheiroZonaNorteRoute: typeof BlogBoxBanheiroZonaNorteRoute
  BlogBoxConvencionalVsAteOTetoRoute: typeof BlogBoxConvencionalVsAteOTetoRoute
  BlogBoxTradicionalVsFlexRoute: typeof BlogBoxTradicionalVsFlexRoute
  BlogCorBoxIncolorFumeVerdeBronzeRoute: typeof BlogCorBoxIncolorFumeVerdeBronzeRoute
  BlogEspelhosLedSobMedidaRoute: typeof BlogEspelhosLedSobMedidaRoute
  BlogFastVidroHistoriaRoute: typeof BlogFastVidroHistoriaRoute
  BlogManutencaoBoxBanheiroRoute: typeof BlogManutencaoBoxBanheiroRoute
  BlogSecureBoxPeliculaProtecaoRoute: typeof BlogSecureBoxPeliculaProtecaoRoute
  BoxDeBanheiroModeloRoute: typeof BoxDeBanheiroModeloRoute
  BoxDeBanheiroEleganceRoute: typeof BoxDeBanheiroEleganceRoute
  BoxDeBanheiroFlexRoute: typeof BoxDeBanheiroFlexRoute
  BoxDeBanheiroNobreRoute: typeof BoxDeBanheiroNobreRoute
  BoxDeBanheiroPisoTetoRoute: typeof BoxDeBanheiroPisoTetoRoute
  BoxDeBanheiroSecureBoxRoute: typeof BoxDeBanheiroSecureBoxRoute
  BoxDeBanheiroTradicionalRoute: typeof BoxDeBanheiroTradicionalRoute
  BoxDeBanheiroTransferRoute: typeof BoxDeBanheiroTransferRoute
  EspelhosModeloRoute: typeof EspelhosModeloRoute
  EspelhosBanheiroRoute: typeof EspelhosBanheiroRoute
  EspelhosBisoteRoute: typeof EspelhosBisoteRoute
  EspelhosLapidadoRoute: typeof EspelhosLapidadoRoute
  EspelhosOrganicoRoute: typeof EspelhosOrganicoRoute
  EspelhosPainelRoute: typeof EspelhosPainelRoute
  PortasDeVidroModeloRoute: typeof PortasDeVidroModeloRoute
  PortasDeVidroAbrirRoute: typeof PortasDeVidroAbrirRoute
  PortasDeVidroCertaRoute: typeof PortasDeVidroCertaRoute
  PortasDeVidroCorrerRoute: typeof PortasDeVidroCorrerRoute
  PortasDeVidroFlexRoute: typeof PortasDeVidroFlexRoute
  PortasDeVidroNobreRoute: typeof PortasDeVidroNobreRoute
  PortasDeVidroVersatikRoute: typeof PortasDeVidroVersatikRoute
  PortasDeVidroVisionRoute: typeof PortasDeVidroVisionRoute
  ProjetosModeloRoute: typeof ProjetosModeloRoute
  ProjetosCoberturasRoute: typeof ProjetosCoberturasRoute
  ProjetosComercialRoute: typeof ProjetosComercialRoute
  ProjetosEscritoriosRoute: typeof ProjetosEscritoriosRoute
  ProjetosFechamentoSacadaRoute: typeof ProjetosFechamentoSacadaRoute
  ProjetosGuardaCorpoRoute: typeof ProjetosGuardaCorpoRoute
  ProjetosResidencialRoute: typeof ProjetosResidencialRoute
  ServicosBairroRoute: typeof ServicosBairroRoute
  BoxDeBanheiroIndexRoute: typeof BoxDeBanheiroIndexRoute
  BoxFumeIndexRoute: typeof BoxFumeIndexRoute
  BoxIncolorIndexRoute: typeof BoxIncolorIndexRoute
  EspelhosIndexRoute: typeof EspelhosIndexRoute
  PortasDeVidroIndexRoute: typeof PortasDeVidroIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos-led': {
      id: '/espelhos-led'
      path: '/espelhos-led'
      fullPath: '/espelhos-led'
      preLoaderRoute: typeof EspelhosLedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/': {
      id: '/portas-de-vidro/'
      path: '/portas-de-vidro'
      fullPath: '/portas-de-vidro/'
      preLoaderRoute: typeof PortasDeVidroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/': {
      id: '/espelhos/'
      path: '/espelhos'
      fullPath: '/espelhos/'
      preLoaderRoute: typeof EspelhosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-incolor/': {
      id: '/box-incolor/'
      path: '/box-incolor'
      fullPath: '/box-incolor/'
      preLoaderRoute: typeof BoxIncolorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-fume/': {
      id: '/box-fume/'
      path: '/box-fume'
      fullPath: '/box-fume/'
      preLoaderRoute: typeof BoxFumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/': {
      id: '/box-de-banheiro/'
      path: '/box-de-banheiro'
      fullPath: '/box-de-banheiro/'
      preLoaderRoute: typeof BoxDeBanheiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$bairro': {
      id: '/servicos/$bairro'
      path: '/servicos/$bairro'
      fullPath: '/servicos/$bairro'
      preLoaderRoute: typeof ServicosBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/residencial': {
      id: '/projetos/residencial'
      path: '/projetos/residencial'
      fullPath: '/projetos/residencial'
      preLoaderRoute: typeof ProjetosResidencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/guarda-corpo': {
      id: '/projetos/guarda-corpo'
      path: '/projetos/guarda-corpo'
      fullPath: '/projetos/guarda-corpo'
      preLoaderRoute: typeof ProjetosGuardaCorpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/fechamento-sacada': {
      id: '/projetos/fechamento-sacada'
      path: '/projetos/fechamento-sacada'
      fullPath: '/projetos/fechamento-sacada'
      preLoaderRoute: typeof ProjetosFechamentoSacadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/escritorios': {
      id: '/projetos/escritorios'
      path: '/projetos/escritorios'
      fullPath: '/projetos/escritorios'
      preLoaderRoute: typeof ProjetosEscritoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/comercial': {
      id: '/projetos/comercial'
      path: '/projetos/comercial'
      fullPath: '/projetos/comercial'
      preLoaderRoute: typeof ProjetosComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/coberturas': {
      id: '/projetos/coberturas'
      path: '/projetos/coberturas'
      fullPath: '/projetos/coberturas'
      preLoaderRoute: typeof ProjetosCoberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$modelo': {
      id: '/projetos/$modelo'
      path: '/projetos/$modelo'
      fullPath: '/projetos/$modelo'
      preLoaderRoute: typeof ProjetosModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/vision': {
      id: '/portas-de-vidro/vision'
      path: '/portas-de-vidro/vision'
      fullPath: '/portas-de-vidro/vision'
      preLoaderRoute: typeof PortasDeVidroVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/versatik': {
      id: '/portas-de-vidro/versatik'
      path: '/portas-de-vidro/versatik'
      fullPath: '/portas-de-vidro/versatik'
      preLoaderRoute: typeof PortasDeVidroVersatikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/nobre': {
      id: '/portas-de-vidro/nobre'
      path: '/portas-de-vidro/nobre'
      fullPath: '/portas-de-vidro/nobre'
      preLoaderRoute: typeof PortasDeVidroNobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/flex': {
      id: '/portas-de-vidro/flex'
      path: '/portas-de-vidro/flex'
      fullPath: '/portas-de-vidro/flex'
      preLoaderRoute: typeof PortasDeVidroFlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/correr': {
      id: '/portas-de-vidro/correr'
      path: '/portas-de-vidro/correr'
      fullPath: '/portas-de-vidro/correr'
      preLoaderRoute: typeof PortasDeVidroCorrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/certa': {
      id: '/portas-de-vidro/certa'
      path: '/portas-de-vidro/certa'
      fullPath: '/portas-de-vidro/certa'
      preLoaderRoute: typeof PortasDeVidroCertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/abrir': {
      id: '/portas-de-vidro/abrir'
      path: '/portas-de-vidro/abrir'
      fullPath: '/portas-de-vidro/abrir'
      preLoaderRoute: typeof PortasDeVidroAbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro/$modelo': {
      id: '/portas-de-vidro/$modelo'
      path: '/portas-de-vidro/$modelo'
      fullPath: '/portas-de-vidro/$modelo'
      preLoaderRoute: typeof PortasDeVidroModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/painel': {
      id: '/espelhos/painel'
      path: '/espelhos/painel'
      fullPath: '/espelhos/painel'
      preLoaderRoute: typeof EspelhosPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/organico': {
      id: '/espelhos/organico'
      path: '/espelhos/organico'
      fullPath: '/espelhos/organico'
      preLoaderRoute: typeof EspelhosOrganicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/lapidado': {
      id: '/espelhos/lapidado'
      path: '/espelhos/lapidado'
      fullPath: '/espelhos/lapidado'
      preLoaderRoute: typeof EspelhosLapidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/bisote': {
      id: '/espelhos/bisote'
      path: '/espelhos/bisote'
      fullPath: '/espelhos/bisote'
      preLoaderRoute: typeof EspelhosBisoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/banheiro': {
      id: '/espelhos/banheiro'
      path: '/espelhos/banheiro'
      fullPath: '/espelhos/banheiro'
      preLoaderRoute: typeof EspelhosBanheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos/$modelo': {
      id: '/espelhos/$modelo'
      path: '/espelhos/$modelo'
      fullPath: '/espelhos/$modelo'
      preLoaderRoute: typeof EspelhosModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/transfer': {
      id: '/box-de-banheiro/transfer'
      path: '/box-de-banheiro/transfer'
      fullPath: '/box-de-banheiro/transfer'
      preLoaderRoute: typeof BoxDeBanheiroTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/tradicional': {
      id: '/box-de-banheiro/tradicional'
      path: '/box-de-banheiro/tradicional'
      fullPath: '/box-de-banheiro/tradicional'
      preLoaderRoute: typeof BoxDeBanheiroTradicionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/secure-box': {
      id: '/box-de-banheiro/secure-box'
      path: '/box-de-banheiro/secure-box'
      fullPath: '/box-de-banheiro/secure-box'
      preLoaderRoute: typeof BoxDeBanheiroSecureBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/piso-teto': {
      id: '/box-de-banheiro/piso-teto'
      path: '/box-de-banheiro/piso-teto'
      fullPath: '/box-de-banheiro/piso-teto'
      preLoaderRoute: typeof BoxDeBanheiroPisoTetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/nobre': {
      id: '/box-de-banheiro/nobre'
      path: '/box-de-banheiro/nobre'
      fullPath: '/box-de-banheiro/nobre'
      preLoaderRoute: typeof BoxDeBanheiroNobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/flex': {
      id: '/box-de-banheiro/flex'
      path: '/box-de-banheiro/flex'
      fullPath: '/box-de-banheiro/flex'
      preLoaderRoute: typeof BoxDeBanheiroFlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/elegance': {
      id: '/box-de-banheiro/elegance'
      path: '/box-de-banheiro/elegance'
      fullPath: '/box-de-banheiro/elegance'
      preLoaderRoute: typeof BoxDeBanheiroEleganceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro/$modelo': {
      id: '/box-de-banheiro/$modelo'
      path: '/box-de-banheiro/$modelo'
      fullPath: '/box-de-banheiro/$modelo'
      preLoaderRoute: typeof BoxDeBanheiroModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/secure-box-pelicula-protecao': {
      id: '/blog_/secure-box-pelicula-protecao'
      path: '/blog/secure-box-pelicula-protecao'
      fullPath: '/blog/secure-box-pelicula-protecao'
      preLoaderRoute: typeof BlogSecureBoxPeliculaProtecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/manutencao-box-banheiro': {
      id: '/blog_/manutencao-box-banheiro'
      path: '/blog/manutencao-box-banheiro'
      fullPath: '/blog/manutencao-box-banheiro'
      preLoaderRoute: typeof BlogManutencaoBoxBanheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/fast-vidro-historia': {
      id: '/blog_/fast-vidro-historia'
      path: '/blog/fast-vidro-historia'
      fullPath: '/blog/fast-vidro-historia'
      preLoaderRoute: typeof BlogFastVidroHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/espelhos-led-sob-medida': {
      id: '/blog_/espelhos-led-sob-medida'
      path: '/blog/espelhos-led-sob-medida'
      fullPath: '/blog/espelhos-led-sob-medida'
      preLoaderRoute: typeof BlogEspelhosLedSobMedidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/cor-box-incolor-fume-verde-bronze': {
      id: '/blog_/cor-box-incolor-fume-verde-bronze'
      path: '/blog/cor-box-incolor-fume-verde-bronze'
      fullPath: '/blog/cor-box-incolor-fume-verde-bronze'
      preLoaderRoute: typeof BlogCorBoxIncolorFumeVerdeBronzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-tradicional-vs-flex': {
      id: '/blog_/box-tradicional-vs-flex'
      path: '/blog/box-tradicional-vs-flex'
      fullPath: '/blog/box-tradicional-vs-flex'
      preLoaderRoute: typeof BlogBoxTradicionalVsFlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-convencional-vs-ate-o-teto': {
      id: '/blog_/box-convencional-vs-ate-o-teto'
      path: '/blog/box-convencional-vs-ate-o-teto'
      fullPath: '/blog/box-convencional-vs-ate-o-teto'
      preLoaderRoute: typeof BlogBoxConvencionalVsAteOTetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-zona-norte': {
      id: '/blog_/box-banheiro-zona-norte'
      path: '/blog/box-banheiro-zona-norte'
      fullPath: '/blog/box-banheiro-zona-norte'
      preLoaderRoute: typeof BlogBoxBanheiroZonaNorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-vila-guilherme': {
      id: '/blog_/box-banheiro-vila-guilherme'
      path: '/blog/box-banheiro-vila-guilherme'
      fullPath: '/blog/box-banheiro-vila-guilherme'
      preLoaderRoute: typeof BlogBoxBanheiroVilaGuilhermeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-vidro-santana': {
      id: '/blog_/box-banheiro-vidro-santana'
      path: '/blog/box-banheiro-vidro-santana'
      fullPath: '/blog/box-banheiro-vidro-santana'
      preLoaderRoute: typeof BlogBoxBanheiroVidroSantanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-tucuruvi': {
      id: '/blog_/box-banheiro-tucuruvi'
      path: '/blog/box-banheiro-tucuruvi'
      fullPath: '/blog/box-banheiro-tucuruvi'
      preLoaderRoute: typeof BlogBoxBanheiroTucuruviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-mandaqui': {
      id: '/blog_/box-banheiro-mandaqui'
      path: '/blog/box-banheiro-mandaqui'
      fullPath: '/blog/box-banheiro-mandaqui'
      preLoaderRoute: typeof BlogBoxBanheiroMandaquiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-jardim-sao-paulo': {
      id: '/blog_/box-banheiro-jardim-sao-paulo'
      path: '/blog/box-banheiro-jardim-sao-paulo'
      fullPath: '/blog/box-banheiro-jardim-sao-paulo'
      preLoaderRoute: typeof BlogBoxBanheiroJardimSaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-banheiro-casa-verde-imirim': {
      id: '/blog_/box-banheiro-casa-verde-imirim'
      path: '/blog/box-banheiro-casa-verde-imirim'
      fullPath: '/blog/box-banheiro-casa-verde-imirim'
      preLoaderRoute: typeof BlogBoxBanheiroCasaVerdeImirimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/box-3-folhas-sistema-versatik': {
      id: '/blog_/box-3-folhas-sistema-versatik'
      path: '/blog/box-3-folhas-sistema-versatik'
      fullPath: '/blog/box-3-folhas-sistema-versatik'
      preLoaderRoute: typeof BlogBox3FolhasSistemaVersatikRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  EspelhosLedRoute: EspelhosLedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogBox3FolhasSistemaVersatikRoute: BlogBox3FolhasSistemaVersatikRoute,
  BlogBoxBanheiroCasaVerdeImirimRoute: BlogBoxBanheiroCasaVerdeImirimRoute,
  BlogBoxBanheiroJardimSaoPauloRoute: BlogBoxBanheiroJardimSaoPauloRoute,
  BlogBoxBanheiroMandaquiRoute: BlogBoxBanheiroMandaquiRoute,
  BlogBoxBanheiroTucuruviRoute: BlogBoxBanheiroTucuruviRoute,
  BlogBoxBanheiroVidroSantanaRoute: BlogBoxBanheiroVidroSantanaRoute,
  BlogBoxBanheiroVilaGuilhermeRoute: BlogBoxBanheiroVilaGuilhermeRoute,
  BlogBoxBanheiroZonaNorteRoute: BlogBoxBanheiroZonaNorteRoute,
  BlogBoxConvencionalVsAteOTetoRoute: BlogBoxConvencionalVsAteOTetoRoute,
  BlogBoxTradicionalVsFlexRoute: BlogBoxTradicionalVsFlexRoute,
  BlogCorBoxIncolorFumeVerdeBronzeRoute: BlogCorBoxIncolorFumeVerdeBronzeRoute,
  BlogEspelhosLedSobMedidaRoute: BlogEspelhosLedSobMedidaRoute,
  BlogFastVidroHistoriaRoute: BlogFastVidroHistoriaRoute,
  BlogManutencaoBoxBanheiroRoute: BlogManutencaoBoxBanheiroRoute,
  BlogSecureBoxPeliculaProtecaoRoute: BlogSecureBoxPeliculaProtecaoRoute,
  BoxDeBanheiroModeloRoute: BoxDeBanheiroModeloRoute,
  BoxDeBanheiroEleganceRoute: BoxDeBanheiroEleganceRoute,
  BoxDeBanheiroFlexRoute: BoxDeBanheiroFlexRoute,
  BoxDeBanheiroNobreRoute: BoxDeBanheiroNobreRoute,
  BoxDeBanheiroPisoTetoRoute: BoxDeBanheiroPisoTetoRoute,
  BoxDeBanheiroSecureBoxRoute: BoxDeBanheiroSecureBoxRoute,
  BoxDeBanheiroTradicionalRoute: BoxDeBanheiroTradicionalRoute,
  BoxDeBanheiroTransferRoute: BoxDeBanheiroTransferRoute,
  EspelhosModeloRoute: EspelhosModeloRoute,
  EspelhosBanheiroRoute: EspelhosBanheiroRoute,
  EspelhosBisoteRoute: EspelhosBisoteRoute,
  EspelhosLapidadoRoute: EspelhosLapidadoRoute,
  EspelhosOrganicoRoute: EspelhosOrganicoRoute,
  EspelhosPainelRoute: EspelhosPainelRoute,
  PortasDeVidroModeloRoute: PortasDeVidroModeloRoute,
  PortasDeVidroAbrirRoute: PortasDeVidroAbrirRoute,
  PortasDeVidroCertaRoute: PortasDeVidroCertaRoute,
  PortasDeVidroCorrerRoute: PortasDeVidroCorrerRoute,
  PortasDeVidroFlexRoute: PortasDeVidroFlexRoute,
  PortasDeVidroNobreRoute: PortasDeVidroNobreRoute,
  PortasDeVidroVersatikRoute: PortasDeVidroVersatikRoute,
  PortasDeVidroVisionRoute: PortasDeVidroVisionRoute,
  ProjetosModeloRoute: ProjetosModeloRoute,
  ProjetosCoberturasRoute: ProjetosCoberturasRoute,
  ProjetosComercialRoute: ProjetosComercialRoute,
  ProjetosEscritoriosRoute: ProjetosEscritoriosRoute,
  ProjetosFechamentoSacadaRoute: ProjetosFechamentoSacadaRoute,
  ProjetosGuardaCorpoRoute: ProjetosGuardaCorpoRoute,
  ProjetosResidencialRoute: ProjetosResidencialRoute,
  ServicosBairroRoute: ServicosBairroRoute,
  BoxDeBanheiroIndexRoute: BoxDeBanheiroIndexRoute,
  BoxFumeIndexRoute: BoxFumeIndexRoute,
  BoxIncolorIndexRoute: BoxIncolorIndexRoute,
  EspelhosIndexRoute: EspelhosIndexRoute,
  PortasDeVidroIndexRoute: PortasDeVidroIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
