/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PortasDeVidroRouteImport } from './routes/portas-de-vidro'
import { Route as EspelhosLedRouteImport } from './routes/espelhos-led'
import { Route as EspelhosRouteImport } from './routes/espelhos'
import { Route as BoxMaisSeguroRouteImport } from './routes/box-mais-seguro'
import { Route as BoxDeBanheiroRouteImport } from './routes/box-de-banheiro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosModeloRouteImport } from './routes/projetos.$modelo'
import { Route as PortasDeVidroModeloRouteImport } from './routes/portas-de-vidro.$modelo'
import { Route as EspelhosModeloRouteImport } from './routes/espelhos.$modelo'
import { Route as BoxDeBanheiroModeloRouteImport } from './routes/box-de-banheiro.$modelo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortasDeVidroRoute = PortasDeVidroRouteImport.update({
  id: '/portas-de-vidro',
  path: '/portas-de-vidro',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosLedRoute = EspelhosLedRouteImport.update({
  id: '/espelhos-led',
  path: '/espelhos-led',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhosRoute = EspelhosRouteImport.update({
  id: '/espelhos',
  path: '/espelhos',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxMaisSeguroRoute = BoxMaisSeguroRouteImport.update({
  id: '/box-mais-seguro',
  path: '/box-mais-seguro',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDeBanheiroRoute = BoxDeBanheiroRouteImport.update({
  id: '/box-de-banheiro',
  path: '/box-de-banheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosModeloRoute = ProjetosModeloRouteImport.update({
  id: '/$modelo',
  path: '/$modelo',
  getParentRoute: () => ProjetosRoute,
} as any)
const PortasDeVidroModeloRoute = PortasDeVidroModeloRouteImport.update({
  id: '/$modelo',
  path: '/$modelo',
  getParentRoute: () => PortasDeVidroRoute,
} as any)
const EspelhosModeloRoute = EspelhosModeloRouteImport.update({
  id: '/$modelo',
  path: '/$modelo',
  getParentRoute: () => EspelhosRoute,
} as any)
const BoxDeBanheiroModeloRoute = BoxDeBanheiroModeloRouteImport.update({
  id: '/$modelo',
  path: '/$modelo',
  getParentRoute: () => BoxDeBanheiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/box-de-banheiro': typeof BoxDeBanheiroRouteWithChildren
  '/box-mais-seguro': typeof BoxMaisSeguroRoute
  '/espelhos': typeof EspelhosRouteWithChildren
  '/espelhos-led': typeof EspelhosLedRoute
  '/portas-de-vidro': typeof PortasDeVidroRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/box-de-banheiro': typeof BoxDeBanheiroRouteWithChildren
  '/box-mais-seguro': typeof BoxMaisSeguroRoute
  '/espelhos': typeof EspelhosRouteWithChildren
  '/espelhos-led': typeof EspelhosLedRoute
  '/portas-de-vidro': typeof PortasDeVidroRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/box-de-banheiro': typeof BoxDeBanheiroRouteWithChildren
  '/box-mais-seguro': typeof BoxMaisSeguroRoute
  '/espelhos': typeof EspelhosRouteWithChildren
  '/espelhos-led': typeof EspelhosLedRoute
  '/portas-de-vidro': typeof PortasDeVidroRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/box-de-banheiro/$modelo': typeof BoxDeBanheiroModeloRoute
  '/espelhos/$modelo': typeof EspelhosModeloRoute
  '/portas-de-vidro/$modelo': typeof PortasDeVidroModeloRoute
  '/projetos/$modelo': typeof ProjetosModeloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/box-de-banheiro'
    | '/box-mais-seguro'
    | '/espelhos'
    | '/espelhos-led'
    | '/portas-de-vidro'
    | '/projetos'
    | '/sitemap.xml'
    | '/box-de-banheiro/$modelo'
    | '/espelhos/$modelo'
    | '/portas-de-vidro/$modelo'
    | '/projetos/$modelo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/box-de-banheiro'
    | '/box-mais-seguro'
    | '/espelhos'
    | '/espelhos-led'
    | '/portas-de-vidro'
    | '/projetos'
    | '/sitemap.xml'
    | '/box-de-banheiro/$modelo'
    | '/espelhos/$modelo'
    | '/portas-de-vidro/$modelo'
    | '/projetos/$modelo'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/box-de-banheiro'
    | '/box-mais-seguro'
    | '/espelhos'
    | '/espelhos-led'
    | '/portas-de-vidro'
    | '/projetos'
    | '/sitemap.xml'
    | '/box-de-banheiro/$modelo'
    | '/espelhos/$modelo'
    | '/portas-de-vidro/$modelo'
    | '/projetos/$modelo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  BoxDeBanheiroRoute: typeof BoxDeBanheiroRouteWithChildren
  BoxMaisSeguroRoute: typeof BoxMaisSeguroRoute
  EspelhosRoute: typeof EspelhosRouteWithChildren
  EspelhosLedRoute: typeof EspelhosLedRoute
  PortasDeVidroRoute: typeof PortasDeVidroRouteWithChildren
  ProjetosRoute: typeof ProjetosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portas-de-vidro': {
      id: '/portas-de-vidro'
      path: '/portas-de-vidro'
      fullPath: '/portas-de-vidro'
      preLoaderRoute: typeof PortasDeVidroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos-led': {
      id: '/espelhos-led'
      path: '/espelhos-led'
      fullPath: '/espelhos-led'
      preLoaderRoute: typeof EspelhosLedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelhos': {
      id: '/espelhos'
      path: '/espelhos'
      fullPath: '/espelhos'
      preLoaderRoute: typeof EspelhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-mais-seguro': {
      id: '/box-mais-seguro'
      path: '/box-mais-seguro'
      fullPath: '/box-mais-seguro'
      preLoaderRoute: typeof BoxMaisSeguroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-de-banheiro': {
      id: '/box-de-banheiro'
      path: '/box-de-banheiro'
      fullPath: '/box-de-banheiro'
      preLoaderRoute: typeof BoxDeBanheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$modelo': {
      id: '/projetos/$modelo'
      path: '/$modelo'
      fullPath: '/projetos/$modelo'
      preLoaderRoute: typeof ProjetosModeloRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/portas-de-vidro/$modelo': {
      id: '/portas-de-vidro/$modelo'
      path: '/$modelo'
      fullPath: '/portas-de-vidro/$modelo'
      preLoaderRoute: typeof PortasDeVidroModeloRouteImport
      parentRoute: typeof PortasDeVidroRoute
    }
    '/espelhos/$modelo': {
      id: '/espelhos/$modelo'
      path: '/$modelo'
      fullPath: '/espelhos/$modelo'
      preLoaderRoute: typeof EspelhosModeloRouteImport
      parentRoute: typeof EspelhosRoute
    }
    '/box-de-banheiro/$modelo': {
      id: '/box-de-banheiro/$modelo'
      path: '/$modelo'
      fullPath: '/box-de-banheiro/$modelo'
      preLoaderRoute: typeof BoxDeBanheiroModeloRouteImport
      parentRoute: typeof BoxDeBanheiroRoute
    }
  }
}

interface BoxDeBanheiroRouteChildren {
  BoxDeBanheiroModeloRoute: typeof BoxDeBanheiroModeloRoute
}

const BoxDeBanheiroRouteChildren: BoxDeBanheiroRouteChildren = {
  BoxDeBanheiroModeloRoute: BoxDeBanheiroModeloRoute,
}

const BoxDeBanheiroRouteWithChildren = BoxDeBanheiroRoute._addFileChildren(
  BoxDeBanheiroRouteChildren,
)

interface EspelhosRouteChildren {
  EspelhosModeloRoute: typeof EspelhosModeloRoute
}

const EspelhosRouteChildren: EspelhosRouteChildren = {
  EspelhosModeloRoute: EspelhosModeloRoute,
}

const EspelhosRouteWithChildren = EspelhosRoute._addFileChildren(
  EspelhosRouteChildren,
)

interface PortasDeVidroRouteChildren {
  PortasDeVidroModeloRoute: typeof PortasDeVidroModeloRoute
}

const PortasDeVidroRouteChildren: PortasDeVidroRouteChildren = {
  PortasDeVidroModeloRoute: PortasDeVidroModeloRoute,
}

const PortasDeVidroRouteWithChildren = PortasDeVidroRoute._addFileChildren(
  PortasDeVidroRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosModeloRoute: typeof ProjetosModeloRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosModeloRoute: ProjetosModeloRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  BoxDeBanheiroRoute: BoxDeBanheiroRouteWithChildren,
  BoxMaisSeguroRoute: BoxMaisSeguroRoute,
  EspelhosRoute: EspelhosRouteWithChildren,
  EspelhosLedRoute: EspelhosLedRoute,
  PortasDeVidroRoute: PortasDeVidroRouteWithChildren,
  ProjetosRoute: ProjetosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
